--- #YAML:1.0
name:                XML-XPathEngine
version:             0.12
abstract:            a re-usable XPath engine for DOM-like trees
license:             ~
author:              
    - Michel Rodriguez <mirod@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
